/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.CardLayout;

/**
 *
 * @author Belthazod
 */
public class AdminUI extends javax.swing.JPanel {
    CardLayout card; 
    /**
     * Creates new form Admin
     */
    public AdminUI() {
        initComponents();
        card = (CardLayout)adminCards.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customerAdminButton = new javax.swing.JButton();
        supplierAdminButton = new javax.swing.JButton();
        productAdminButton = new javax.swing.JButton();
        backupAdminButton = new javax.swing.JButton();
        userAdminButton = new javax.swing.JButton();
        logsAdminButton = new javax.swing.JButton();
        adminCards = new javax.swing.JPanel();
        customerPanel = new VIEW.CustomerUI();
        productsPanel = new VIEW.ProductsUI();
        supplierPanel = new VIEW.SupplierUI();
        backUpPanel = new VIEW.BackUp();
        userPanel = new VIEW.UserUI();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(240, 177, 78));
        setForeground(new java.awt.Color(255, 255, 255));
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(250, 238, 161));

        customerAdminButton.setText("Customer");
        customerAdminButton.setEnabled(false);
        customerAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAdminButtonActionPerformed(evt);
            }
        });

        supplierAdminButton.setText("Supplier");
        supplierAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierAdminButtonActionPerformed(evt);
            }
        });

        productAdminButton.setText("Product");
        productAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAdminButtonActionPerformed(evt);
            }
        });

        backupAdminButton.setText("Back Up");
        backupAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupAdminButtonActionPerformed(evt);
            }
        });

        userAdminButton.setText("User");
        userAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAdminButtonActionPerformed(evt);
            }
        });

        logsAdminButton.setText("Logs");
        logsAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backupAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logsAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(customerAdminButton)
                .addGap(30, 30, 30)
                .addComponent(supplierAdminButton)
                .addGap(30, 30, 30)
                .addComponent(productAdminButton)
                .addGap(29, 29, 29)
                .addComponent(backupAdminButton)
                .addGap(27, 27, 27)
                .addComponent(userAdminButton)
                .addGap(26, 26, 26)
                .addComponent(logsAdminButton)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        adminCards.setLayout(new java.awt.CardLayout());

        customerPanel.setBackground(new java.awt.Color(250, 238, 161));
        customerPanel.setForeground(new java.awt.Color(255, 255, 255));
        adminCards.add(customerPanel, "customerCard");
        adminCards.add(productsPanel, "productCard");
        adminCards.add(supplierPanel, "supplierCard");
        adminCards.add(backUpPanel, "backupCard");
        adminCards.add(userPanel, "userCard");

        jLabel1.setFont(new java.awt.Font("Open Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adminCards, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adminCards, javax.swing.GroupLayout.PREFERRED_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customerAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAdminButtonActionPerformed

        card.show(adminCards, "customerCard");
        
        userAdminButton.setEnabled(true);
        logsAdminButton.setEnabled(true);
        supplierAdminButton.setEnabled(true); 
        customerAdminButton.setEnabled(false);
        productAdminButton.setEnabled(true);
        backupAdminButton.setEnabled(true);
    }//GEN-LAST:event_customerAdminButtonActionPerformed

    private void productAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productAdminButtonActionPerformed

        card.show(adminCards, "productCard");
        
        userAdminButton.setEnabled(true);
        logsAdminButton.setEnabled(true);
        productAdminButton.setEnabled(false);
        customerAdminButton.setEnabled(true);
        supplierAdminButton.setEnabled(true);
        backupAdminButton.setEnabled(true);
    }//GEN-LAST:event_productAdminButtonActionPerformed

    private void supplierAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierAdminButtonActionPerformed

        card.show(adminCards, "supplierCard");
        
        userAdminButton.setEnabled(true);
        logsAdminButton.setEnabled(true);
        productAdminButton.setEnabled(true);
        customerAdminButton.setEnabled(true);
        supplierAdminButton.setEnabled(false);
        backupAdminButton.setEnabled(true);
    }//GEN-LAST:event_supplierAdminButtonActionPerformed

    private void backupAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupAdminButtonActionPerformed

        card.show(adminCards, "backupCard");
        
        userAdminButton.setEnabled(true);
        logsAdminButton.setEnabled(true);
        backupAdminButton.setEnabled(false);
        productAdminButton.setEnabled(true);
        customerAdminButton.setEnabled(true);
        supplierAdminButton.setEnabled(true);
    }//GEN-LAST:event_backupAdminButtonActionPerformed

    private void userAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAdminButtonActionPerformed
        card.show(adminCards, "userCard");
        
        userAdminButton.setEnabled(false);
        logsAdminButton.setEnabled(true);
        backupAdminButton.setEnabled(true);
        productAdminButton.setEnabled(true);
        customerAdminButton.setEnabled(true);
        supplierAdminButton.setEnabled(true);
        logsAdminButton.setEnabled(true);
    }//GEN-LAST:event_userAdminButtonActionPerformed

    private void logsAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsAdminButtonActionPerformed
        card.show(adminCards, "logsCard");
        
        userAdminButton.setEnabled(true);
        logsAdminButton.setEnabled(false);
        backupAdminButton.setEnabled(true);
        productAdminButton.setEnabled(true);
        customerAdminButton.setEnabled(true);
        supplierAdminButton.setEnabled(true);
        logsAdminButton.setEnabled(true);
    }//GEN-LAST:event_logsAdminButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminCards;
    private VIEW.BackUp backUpPanel;
    private javax.swing.JButton backupAdminButton;
    private javax.swing.JButton customerAdminButton;
    private VIEW.CustomerUI customerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logsAdminButton;
    private javax.swing.JButton productAdminButton;
    private VIEW.ProductsUI productsPanel;
    private javax.swing.JButton supplierAdminButton;
    private VIEW.SupplierUI supplierPanel;
    private javax.swing.JButton userAdminButton;
    private VIEW.UserUI userPanel;
    // End of variables declaration//GEN-END:variables
}
