/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import BEANS.ComboItem;
import VIEW.SecondhandTradeIn;
import CONTROLLERS.CategoryController;
import CONTROLLERS.ProductController;
import UTIL.InputValidator;
import javax.swing.ButtonGroup;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Belthazod
 */
public class ProductsUI extends javax.swing.JPanel {
    static ProductController productController;
    static CategoryController categoryController;
    ButtonGroup reorderQuantityLevelGroup = new ButtonGroup();
    ButtonGroup warrantyGroup = new ButtonGroup();
    /**
     * Creates new form AddProduct
     */
    public ProductsUI() {
        initComponents();
        
        try{
        productController = new ProductController(adminProductsTable, InventoryUI.getInventoryTable(), TransferUI.getTransferProductsTable(), DeliveryUI.getDeliveryProductsTable(), productsTab, CriticalProducts.getCriticalProductsTable(), ProductTrade.getProductsTable() );
        categoryController = new CategoryController(categoryTable, addProductCategoryComboBox, editProductCategoryComboBox, SecondhandTradeIn.getSecondHandCategoryComboBox(), categoryIDEditInput, categoryEditInput, editCategoryDialog);
        adminProductsTable.getColumnModel().getColumn(0).setMaxWidth(0);
        adminProductsTable.getColumnModel().getColumn(0).setMinWidth(0);
        adminProductsTable.getColumnModel().getColumn(0).setPreferredWidth(0);

        categoryTable.getColumnModel().getColumn(0).setMaxWidth(0);
        categoryTable.getColumnModel().getColumn(0).setMinWidth(0);
        categoryTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        editCategoryDialog.setLocationRelativeTo(null);
        editProductDialog.setLocationRelativeTo(null);
        }catch(NullPointerException npe){
            npe.printStackTrace();
        }
        InputValidator.enabler(adminProductsTable, editProductButton);
        InputValidator.enabler(adminProductsTable, deleteProductButton);
        InputValidator.enabler(categoryTable, jButton4);
        InputValidator.enabler(categoryTable, editCategoryButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editProductDialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        productNameEditInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editProductCategoryComboBox = new javax.swing.JComboBox<ComboItem>();
        jLabel11 = new javax.swing.JLabel();
        editProductSupplierComboBox = new javax.swing.JComboBox<ComboItem>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        quantityEditInput = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        reorderQuantityEditSpinner = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        productIDEditInput = new javax.swing.JLabel();
        productIDEditInput.setVisible(false);
        unitEditComboBox = new javax.swing.JComboBox<String>();
        jLabel19 = new javax.swing.JLabel();
        warrantyEditSpinner = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        editCategoryDialog = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        categoryEditInput = new javax.swing.JTextField();
        saveEditCategoryButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        categoryIDEditInput = new javax.swing.JLabel();
        productsTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productNameInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        quantityInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        addProductCategoryComboBox = new javax.swing.JComboBox<ComboItem>();
        jLabel7 = new javax.swing.JLabel();
        AddProductButton = new javax.swing.JButton();
        addProductSupplierComboBox = new javax.swing.JComboBox<ComboItem>();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        warrantySpinner = new javax.swing.JSpinner();
        reorderLevelEnableRadioButton = new javax.swing.JRadioButton();
        reorderLevelDisableRadioButton = new javax.swing.JRadioButton();
        unitComboBox = new javax.swing.JComboBox<String>();
        jLabel18 = new javax.swing.JLabel();
        warrantyEnableRadioButton = new javax.swing.JRadioButton();
        warrantyDisableRadioButton = new javax.swing.JRadioButton();
        reorderQuantityLevelSpinner = new javax.swing.JSpinner();
        warrantyMonthsLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adminProductsTable = new javax.swing.JTable();
        editProductButton = new javax.swing.JButton();
        deleteProductButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        categoryNameInput = new javax.swing.JTextField();
        editCategoryButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        addNewCategoryButton = new javax.swing.JButton();

        editProductDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editProductDialog.setTitle("Edit Product Details");
        editProductDialog.setBounds(new java.awt.Rectangle(0, 0, 500, 400));
        editProductDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProductDialog.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel8.setText("Product Name: ");

        productNameEditInput.setText("jTextField1");
        productNameEditInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameEditInputActionPerformed(evt);
            }
        });

        jLabel9.setText("Category:");

        editProductCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Supplier:");

        editProductSupplierComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Unit:");

        jLabel13.setText("Physical Count:");

        quantityEditInput.setText("jLabel14");

        jLabel15.setText("Reorder Quantity Level:");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        productIDEditInput.setText("jLabel17");

        unitEditComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "piece", "bottle", "box", "roll" }));

        jLabel19.setText("Warranty:");

        jLabel20.setText("months");

        javax.swing.GroupLayout editProductDialogLayout = new javax.swing.GroupLayout(editProductDialog.getContentPane());
        editProductDialog.getContentPane().setLayout(editProductDialogLayout);
        editProductDialogLayout.setHorizontalGroup(
            editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProductDialogLayout.createSequentialGroup()
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(productNameEditInput, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(productIDEditInput))
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(77, 77, 77)
                        .addComponent(unitEditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9)
                        .addGap(51, 51, 51)
                        .addComponent(editProductCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11)
                        .addGap(58, 58, 58)
                        .addComponent(editProductSupplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addGap(46, 46, 46)
                        .addComponent(quantityEditInput))
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)
                        .addGap(14, 14, 14)
                        .addComponent(reorderQuantityEditSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19)
                        .addGap(80, 80, 80)
                        .addComponent(warrantyEditSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jButton3)
                        .addGap(43, 43, 43)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        editProductDialogLayout.setVerticalGroup(
            editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProductDialogLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productIDEditInput)
                    .addGroup(editProductDialogLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productNameEditInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(unitEditComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(editProductCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(editProductSupplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(quantityEditInput))
                .addGap(16, 16, 16)
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(reorderQuantityEditSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(warrantyEditSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(30, 30, 30)
                .addGroup(editProductDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editCategoryDialog.setBounds(new java.awt.Rectangle(0, 0, 450, 200));

        jLabel17.setText("Category Name:");

        saveEditCategoryButton.setText("Save");
        saveEditCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditCategoryButtonActionPerformed(evt);
            }
        });

        jButton6.setText("Cancel");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        categoryIDEditInput.setText("jLabel18");
        categoryIDEditInput.setEnabled(false);
        categoryIDEditInput.setVisible(false);

        javax.swing.GroupLayout editCategoryDialogLayout = new javax.swing.GroupLayout(editCategoryDialog.getContentPane());
        editCategoryDialog.getContentPane().setLayout(editCategoryDialogLayout);
        editCategoryDialogLayout.setHorizontalGroup(
            editCategoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCategoryDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editCategoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(editCategoryDialogLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveEditCategoryButton))
                    .addGroup(editCategoryDialogLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryEditInput, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editCategoryDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(categoryIDEditInput)
                .addContainerGap())
        );
        editCategoryDialogLayout.setVerticalGroup(
            editCategoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editCategoryDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(categoryIDEditInput)
                .addGap(28, 28, 28)
                .addGroup(editCategoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(categoryEditInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(editCategoryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveEditCategoryButton)
                    .addComponent(jButton6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(250, 238, 161));
        setMaximumSize(new java.awt.Dimension(814, 592));
        setPreferredSize(new java.awt.Dimension(814, 592));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productsTab.setBackground(new java.awt.Color(250, 238, 161));

        jPanel1.setBackground(new java.awt.Color(250, 238, 161));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Product Name:");

        productNameInput.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        productNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Quantity:");

        quantityInput.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Re- order Level:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Unit of measurement:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Category:");

        addProductCategoryComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addProductCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Accessories" }));
        addProductCategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductCategoryComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Supplier:");

        AddProductButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        AddProductButton.setText("Add New Product");
        AddProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProductButtonActionPerformed(evt);
            }
        });

        addProductSupplierComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addProductSupplierComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addProductSupplierComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductSupplierComboBoxActionPerformed(evt);
            }
        });

        warrantySpinner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warrantySpinner.setEnabled(false);

        reorderLevelEnableRadioButton.setBackground(new java.awt.Color(250, 238, 161));
        reorderLevelEnableRadioButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reorderLevelEnableRadioButton.setText("Enabled");
        reorderLevelEnableRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reorderLevelEnableRadioButtonActionPerformed(evt);
            }
        });

        reorderLevelDisableRadioButton.setBackground(new java.awt.Color(250, 238, 161));
        reorderLevelDisableRadioButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        reorderLevelDisableRadioButton.setText("Disabled");
        reorderLevelDisableRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reorderLevelDisableRadioButtonActionPerformed(evt);
            }
        });

        unitComboBox.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        unitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "piece", "bottle", "box", "roll" }));
        unitComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitComboBoxActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel18.setText("Warranty:");

        warrantyEnableRadioButton.setBackground(new java.awt.Color(250, 238, 161));
        warrantyEnableRadioButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        warrantyEnableRadioButton.setText("Enabled");
        warrantyEnableRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrantyEnableRadioButtonActionPerformed(evt);
            }
        });

        warrantyDisableRadioButton.setBackground(new java.awt.Color(250, 238, 161));
        warrantyDisableRadioButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        warrantyDisableRadioButton.setText("Disabled");
        warrantyDisableRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warrantyDisableRadioButtonActionPerformed(evt);
            }
        });

        reorderQuantityLevelSpinner.setEnabled(false);

        warrantyMonthsLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        warrantyMonthsLabel.setText("months");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(productNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(17, 17, 17)
                        .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(47, 47, 47)
                        .addComponent(addProductSupplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(38, 38, 38)
                        .addComponent(addProductCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(reorderQuantityLevelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(reorderLevelEnableRadioButton)
                    .addComponent(reorderLevelDisableRadioButton)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(80, 80, 80)
                        .addComponent(warrantySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(warrantyMonthsLabel))
                    .addComponent(warrantyEnableRadioButton)
                    .addComponent(warrantyDisableRadioButton)
                    .addComponent(AddProductButton)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1))
                    .addComponent(productNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3))
                    .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(addProductSupplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(addProductCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addComponent(reorderQuantityLevelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(reorderLevelEnableRadioButton)
                .addGap(5, 5, 5)
                .addComponent(reorderLevelDisableRadioButton)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warrantySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(warrantyMonthsLabel))))
                .addComponent(warrantyEnableRadioButton)
                .addGap(7, 7, 7)
                .addComponent(warrantyDisableRadioButton)
                .addGap(7, 7, 7)
                .addComponent(AddProductButton))
        );

        warrantySpinner.setVisible(false);
        reorderQuantityLevelGroup.add(reorderLevelEnableRadioButton);
        reorderLevelDisableRadioButton.setSelected(true);
        reorderQuantityLevelGroup.add(reorderLevelDisableRadioButton);
        warrantyGroup.add(warrantyEnableRadioButton);
        warrantyDisableRadioButton.setSelected(true);
        warrantyGroup.add(warrantyDisableRadioButton);
        reorderQuantityLevelSpinner.setVisible(false);
        warrantyMonthsLabel.setVisible(false);

        productsTab.addTab("Add Product", jPanel1);

        jPanel2.setBackground(new java.awt.Color(250, 238, 161));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminProductsTable.setAutoCreateRowSorter(true);
        adminProductsTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        adminProductsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Product Name", "Category", "Unit", "Supplier", "Warranty(months)", "Physical Count", "Reorder Quantity Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        adminProductsTable.setName(""); // NOI18N
        jScrollPane1.setViewportView(adminProductsTable);
        if (adminProductsTable.getColumnModel().getColumnCount() > 0) {
            adminProductsTable.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, 795, 410));

        editProductButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        editProductButton.setText("Edit Product");
        editProductButton.setEnabled(false);
        editProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductButtonActionPerformed(evt);
            }
        });
        jPanel2.add(editProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, -1));

        deleteProductButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteProductButton.setText("Delete Product");
        deleteProductButton.setEnabled(false);
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });
        jPanel2.add(deleteProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, -1, -1));

        productsTab.addTab("Edit Product", jPanel2);

        jPanel3.setBackground(new java.awt.Color(250, 238, 161));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoryTable.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "type_id", "Category Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(categoryTable);
        categoryTable.getColumnModel().getColumn(0).setMaxWidth(0);
        categoryTable.getColumnModel().getColumn(0).setMinWidth(0);
        categoryTable.getColumnModel().getColumn(0).setPreferredWidth(0);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 610, 230));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("Category List");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Category Name:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        categoryNameInput.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        categoryNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryNameInputActionPerformed(evt);
            }
        });
        jPanel3.add(categoryNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 500, -1));

        editCategoryButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        editCategoryButton.setText("Edit Category");
        editCategoryButton.setEnabled(false);
        editCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCategoryButtonActionPerformed(evt);
            }
        });
        jPanel3.add(editCategoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton4.setText("Delete Category");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, -1, -1));

        addNewCategoryButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addNewCategoryButton.setText("Add to Category List");
        addNewCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCategoryButtonActionPerformed(evt);
            }
        });
        jPanel3.add(addNewCategoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        productsTab.addTab("Add/Edit Category", jPanel3);

        add(productsTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));
    }// </editor-fold>//GEN-END:initComponents

    
    private void productNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameInputActionPerformed

    private void addProductSupplierComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductSupplierComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProductSupplierComboBoxActionPerformed

    private void addProductCategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductCategoryComboBoxActionPerformed
        // TODO add your handling code here:
        System.out.println("Selected value = " +  evt.getActionCommand());
    }//GEN-LAST:event_addProductCategoryComboBoxActionPerformed

    private void AddProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductButtonActionPerformed
        String s = "";
            String name = productNameInput.getText();
            boolean exists = false;
            for (int i=0; i<adminProductsTable.getRowCount(); i++) {    
            s = adminProductsTable.getValueAt(i, 1).toString().trim();
            if(name.equals(s)){
            exists = true;
            break;
            }
            }
            if(!exists){ 
            productController.addProduct(productNameInput, quantityInput, unitComboBox, addProductSupplierComboBox, addProductCategoryComboBox, reorderQuantityLevelSpinner, warrantySpinner);    
            productController.updateTableContents();
            }else{ 
            JOptionPane.showMessageDialog(null, "Item already exist.","message",JOptionPane.PLAIN_MESSAGE);
            }          
    }//GEN-LAST:event_AddProductButtonActionPerformed

    private void reorderLevelEnableRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reorderLevelEnableRadioButtonActionPerformed
        if(reorderLevelEnableRadioButton.isSelected()){
            reorderQuantityLevelSpinner.setEnabled(true);
            reorderQuantityLevelSpinner.setVisible(true);
        }
    }//GEN-LAST:event_reorderLevelEnableRadioButtonActionPerformed

    private void reorderLevelDisableRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reorderLevelDisableRadioButtonActionPerformed
        if(reorderLevelDisableRadioButton.isSelected()){
            reorderQuantityLevelSpinner.setEnabled(false);
            reorderQuantityLevelSpinner.setVisible(false);
            reorderQuantityLevelSpinner.setValue(0);
        }
    }//GEN-LAST:event_reorderLevelDisableRadioButtonActionPerformed

    private void editProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductButtonActionPerformed
        Integer selectedRow = adminProductsTable.getSelectedRow();
        String result = (String) adminProductsTable.getModel().getValueAt(selectedRow, 0);
        productController.openProductEditDialog(result, productIDEditInput, productNameEditInput, editProductCategoryComboBox, editProductSupplierComboBox, unitEditComboBox, quantityEditInput, reorderQuantityEditSpinner, warrantyEditSpinner);
        editProductDialog.setVisible(true);
    }//GEN-LAST:event_editProductButtonActionPerformed

    private void productNameEditInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameEditInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameEditInputActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        productController.editProduct(editProductDialog, productIDEditInput, productNameEditInput, quantityEditInput, unitEditComboBox, editProductSupplierComboBox, editProductCategoryComboBox, reorderQuantityEditSpinner, warrantyEditSpinner);
        productController.updateTableContents();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addNewCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCategoryButtonActionPerformed
        String s = "";
            String name = categoryNameInput.getText();
            boolean exists = false;
            for (int i=0; i<categoryTable.getRowCount(); i++) {    
            s = categoryTable.getValueAt(i, 1).toString().trim();
            if(name.equals(s)){
            exists = true;
            break;
            }
            }
            if(!exists){ 
            categoryController.addCategory(categoryNameInput);
            categoryController.updateCategoryTable();
            }else{ 
            JOptionPane.showMessageDialog(null, "Category already exist.","message",JOptionPane.PLAIN_MESSAGE);
            }       
    }//GEN-LAST:event_addNewCategoryButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Integer selectedRow = categoryTable.getSelectedRow();
        String categoryName = (String) categoryTable.getModel().getValueAt(selectedRow, 1);
        int result = JOptionPane.showConfirmDialog(null, "Are you sure in deleting " + categoryName + " from the Category List","Warning!" ,JOptionPane.YES_NO_OPTION);
               String s = "";
            String name = categoryNameInput.getText();
            boolean exists = false;
            for (int i=0; i<categoryTable.getRowCount(); i++) {    
            s = categoryTable.getValueAt(i, 1).toString().trim();
            if(name.equals(s)){
            exists = true;
            break;
            }
            }
            if(!exists){ 
            if(result == 0){
            categoryController.deleteCategory();
            categoryController.updateCategoryTable();
            }
            }else{ 
            JOptionPane.showMessageDialog(null, "Category already exist.","message",JOptionPane.PLAIN_MESSAGE);
            }  

    }//GEN-LAST:event_jButton4ActionPerformed

    private void editCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCategoryButtonActionPerformed
        Integer selectedRow = categoryTable.getSelectedRow();
        String result = (String) categoryTable.getModel().getValueAt(selectedRow, 0);
        
        if(categoryController.openEditDialog(result, categoryEditInput, categoryIDEditInput)){
            editCategoryDialog.setVisible(true);
        }
        editCategoryDialog.setVisible(true);
    }//GEN-LAST:event_editCategoryButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        editCategoryDialog.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        editProductDialog.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        Integer selectedRow = adminProductsTable.getSelectedRow();
        String name = (String) adminProductsTable.getModel().getValueAt(selectedRow, 1);
        int result = JOptionPane.showConfirmDialog(null, "Are you sure in deleting " + name + " from the Products List","Warning!" ,JOptionPane.YES_NO_OPTION);
        
        if(result == 0){
            productController.deleteSelectedProduct();
            productController.updateTableContents();
        }
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    private void unitComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitComboBoxActionPerformed

    private void warrantyEnableRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrantyEnableRadioButtonActionPerformed
        if(warrantyEnableRadioButton.isSelected()){
            warrantySpinner.setEnabled(true);
            warrantySpinner.setVisible(true);
            warrantyMonthsLabel.setVisible(true);
        }
    }//GEN-LAST:event_warrantyEnableRadioButtonActionPerformed

    private void warrantyDisableRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warrantyDisableRadioButtonActionPerformed
        if(warrantyDisableRadioButton.isSelected()){
            warrantySpinner.setEnabled(false);
            warrantySpinner.setVisible(false);
            warrantyMonthsLabel.setVisible(false);
            warrantySpinner.setValue(0);
        }
    }//GEN-LAST:event_warrantyDisableRadioButtonActionPerformed

    private void saveEditCategoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditCategoryButtonActionPerformed
        categoryController.editCategory();
    }//GEN-LAST:event_saveEditCategoryButtonActionPerformed

    private void categoryNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryNameInputActionPerformed

    public static void updateAdminProductsTable(){
        productController.updateTableContents();
    }

    public static void updateCategoryTable(){
        categoryController.updateCategoryTable();
    }
    
    public static JComboBox getAddProductSupplierComboBox(){
        return addProductSupplierComboBox;
    }
    
    public static JComboBox getEditProductSupplierComboBox(){
        return editProductSupplierComboBox;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProductButton;
    private javax.swing.JButton addNewCategoryButton;
    private static javax.swing.JComboBox<ComboItem> addProductCategoryComboBox;
    private static javax.swing.JComboBox<ComboItem> addProductSupplierComboBox;
    private static javax.swing.JTable adminProductsTable;
    private javax.swing.JTextField categoryEditInput;
    private javax.swing.JLabel categoryIDEditInput;
    private javax.swing.JTextField categoryNameInput;
    private static javax.swing.JTable categoryTable;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JButton editCategoryButton;
    private javax.swing.JDialog editCategoryDialog;
    private javax.swing.JButton editProductButton;
    private javax.swing.JComboBox<ComboItem> editProductCategoryComboBox;
    private javax.swing.JDialog editProductDialog;
    private static javax.swing.JComboBox<ComboItem> editProductSupplierComboBox;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel productIDEditInput;
    private javax.swing.JTextField productNameEditInput;
    private javax.swing.JTextField productNameInput;
    private javax.swing.JTabbedPane productsTab;
    private javax.swing.JLabel quantityEditInput;
    private javax.swing.JTextField quantityInput;
    private javax.swing.JRadioButton reorderLevelDisableRadioButton;
    private javax.swing.JRadioButton reorderLevelEnableRadioButton;
    private javax.swing.JSpinner reorderQuantityEditSpinner;
    private javax.swing.JSpinner reorderQuantityLevelSpinner;
    private javax.swing.JButton saveEditCategoryButton;
    private javax.swing.JComboBox<String> unitComboBox;
    private javax.swing.JComboBox<String> unitEditComboBox;
    private javax.swing.JRadioButton warrantyDisableRadioButton;
    private javax.swing.JSpinner warrantyEditSpinner;
    private javax.swing.JRadioButton warrantyEnableRadioButton;
    private javax.swing.JLabel warrantyMonthsLabel;
    private javax.swing.JSpinner warrantySpinner;
    // End of variables declaration//GEN-END:variables
}
