/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itprojectii;

import java.awt.CardLayout;

/**
 *
 * @author weak_2030
 */
public class Admin extends javax.swing.JPanel {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customerAdminButton = new javax.swing.JButton();
        supplierAdminButton = new javax.swing.JButton();
        productAdminButton = new javax.swing.JButton();
        adminCards = new javax.swing.JPanel();
        addCustomer1 = new itprojectii.AddCustomer();
        addSupplier1 = new itprojectii.AddSupplier();
        addProduct1 = new itprojectii.AddProduct();

        setBackground(new java.awt.Color(255, 255, 255));

        customerAdminButton.setText("Customer");
        customerAdminButton.setEnabled(false);
        customerAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAdminButtonActionPerformed(evt);
            }
        });

        supplierAdminButton.setText("Supplier");
        supplierAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierAdminButtonActionPerformed(evt);
            }
        });

        productAdminButton.setText("Product");
        productAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(customerAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(supplierAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(customerAdminButton)
                .addGap(30, 30, 30)
                .addComponent(supplierAdminButton)
                .addGap(30, 30, 30)
                .addComponent(productAdminButton)
                .addContainerGap(517, Short.MAX_VALUE))
        );

        adminCards.setLayout(new java.awt.CardLayout());
        adminCards.add(addCustomer1, "addCustomerCard");
        addCustomer1.getAccessibleContext().setAccessibleName("");

        adminCards.add(addSupplier1, "addSupplierCard");
        adminCards.add(addProduct1, "addProductCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(adminCards, javax.swing.GroupLayout.PREFERRED_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminCards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customerAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAdminButtonActionPerformed
        CardLayout card = (CardLayout)adminCards.getLayout();
        card.show(adminCards, "addCustomerCard");
        supplierAdminButton.setEnabled(true); 
        customerAdminButton.setEnabled(false);
        productAdminButton.setEnabled(true);
    }//GEN-LAST:event_customerAdminButtonActionPerformed

    private void productAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productAdminButtonActionPerformed
        CardLayout card = (CardLayout)adminCards.getLayout();
        card.show(adminCards, "addProductCard");
        
        productAdminButton.setEnabled(false);
        customerAdminButton.setEnabled(true);
        supplierAdminButton.setEnabled(true);
    }//GEN-LAST:event_productAdminButtonActionPerformed

    private void supplierAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierAdminButtonActionPerformed
        CardLayout card = (CardLayout)adminCards.getLayout();
        card.show(adminCards, "addSupplierCard");
        
        productAdminButton.setEnabled(true);
        customerAdminButton.setEnabled(true);
        supplierAdminButton.setEnabled(false);
    }//GEN-LAST:event_supplierAdminButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private itprojectii.AddCustomer addCustomer1;
    private itprojectii.AddProduct addProduct1;
    private itprojectii.AddSupplier addSupplier1;
    private javax.swing.JPanel adminCards;
    private javax.swing.JButton customerAdminButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton productAdminButton;
    private javax.swing.JButton supplierAdminButton;
    // End of variables declaration//GEN-END:variables
}
